#!/bin/bash
# DEPRECATED: This script is deprecated.
# Please use: python -m homeschool setup
# See README.md for the new workflow.
#
# Homeschool Setup Script
# This script guides users through initial configuration and launches services

# Text colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to display help
show_help() {
    echo -e "${GREEN}Homeschool Setup Script${NC}"
    echo "Usage: ./setup.sh [options]"
    echo ""
    echo "Options:"
    echo "  -h, --help    Show this help message"
    echo ""
    echo "This script will:"
    echo "  1. Guide you through configuring required paths and settings"
    echo "  2. Create a personalized config.yaml file"
    echo "  3. Launch Docker services using docker compose"
    echo ""
    echo "You only need to run this script once. For subsequent runs, use:"
    echo "  docker compose up -d"
}

# Function to validate path
validate_path() {
    local path="$1"
    local description="$2"
    
    # Check if path is empty
    if [[ -z "$path" ]]; then
        echo -e "${RED}Error: $description cannot be empty.${NC}"
        return 1
    fi
    
    # Expand ~ to home directory
    local expanded_path
    expanded_path="${path/\~/$HOME}"
    
    # For paths (not tokens), check if directory exists
    if [[ "$description" != *"ChromaDB auth token"* ]]; then
        if [[ ! -d "$expanded_path" ]]; then
            echo -e "${YELLOW}Warning: $description '$path' does not exist.${NC}"
            read -p "Do you want to continue anyway? (y/N): " choice
            if [[ ! "$choice" =~ ^[Yy]$ ]]; then
                return 1
            fi
        fi
    fi
    
    return 0
}

# Function to generate random token
generate_token() {
    openssl rand -hex 32
}

# Welcome message
echo -e "${GREEN}Welcome to Homeschool Setup!${NC}"
echo "This script will help you configure your Homeschool environment."
echo "You'll need to provide:"
echo "  1. Vault path (location of your Obsidian notes)"
echo "  2. Model store path (where your .gguf files are stored)"
echo "  3. ChromaDB auth token (can be auto-generated)"
echo "  4. Database selection (default/essay/homework/etc.)"
echo ""

# Ask if user wants help
read -p "Do you want to see help/usage instructions? (y/N): " show_help_choice
if [[ "$show_help_choice" =~ ^[Yy]$ ]]; then
    show_help
    echo ""
fi

# Gather configuration information
echo -e "${YELLOW}Please provide the following configuration values:${NC}"

# Vault path
while true; do
    read -p "Enter your Obsidian vault path: " vault_path
    if validate_path "$vault_path" "Vault path"; then
        break
    fi
done

# Model store path
while true; do
    read -p "Enter your model store path (for .gguf files): " model_store_path
    if validate_path "$model_store_path" "Model store path"; then
        break
    fi
done

# ChromaDB auth token
echo -e "${YELLOW}ChromaDB auth token:${NC}"
while true; do
    read -p "Do you want to auto-generate a secure token? (Y/n): " auto_gen_choice
    auto_gen_choice=${auto_gen_choice:-Y}  # Default to Y if empty
    if [[ "$auto_gen_choice" =~ ^[YyNn]$ ]]; then
        break
    else
        echo -e "${RED}Please enter Y or N.${NC}"
    fi
done

if [[ "$auto_gen_choice" =~ ^[Nn]$ ]]; then
    while true; do
        read -p "Enter your ChromaDB auth token (64 hex characters): " chromadb_token
        # Basic validation - should be 64 hex characters (32 bytes)
        if [[ "$chromadb_token" =~ ^[0-9a-fA-F]{64}$ ]]; then
            break
        else
            echo -e "${RED}Invalid token format. Please enter 64 hexadecimal characters.${NC}"
        fi
    done
else
    chromadb_token=$(generate_token)
    echo -e "${GREEN}Generated ChromaDB auth token: $chromadb_token${NC}"
fi

# Database selection
echo -e "${YELLOW}Database selection:${NC}"
echo "Available databases: default, essay, homework"
while true; do
    read -p "Enter database name to use (default: default): " db_selection
    db_selection=${db_selection:-default}  # Default to 'default' if empty
    
    # Validate database selection
    case "$db_selection" in
        default|essay|homework)
            break
            ;;
        *)
            echo -e "${YELLOW}Invalid database selection. Please choose from: default, essay, homework${NC}"
            ;;
    esac
done

# Create config.yaml from template
echo -e "${GREEN}Creating config.yaml...${NC}"

# Read the current config.yaml as template and replace values
cat > config.yaml << EOF
# Homeschool Configuration
# Generated by setup.sh - customize values as needed

hardware:
  gpu: "cpu"  # Options: cpu, nvidia, metal

network:
  bind_host: "localhost"
  ports:
    chromadb: 8000

paths:
  vault: "$vault_path"
  model_store: "$model_store_path"
  manifest_dir: null  # Uses default: ~/.sovereign_brain/manifest

embedding:
  model_file: "nomic-embed-text-v1.5.Q4_K_M.gguf"
  n_ctx: 512
  n_gpu_layers: 32
  split_headers:
    - "#"
    - "##"
    - "###"
  embed_batch_size: 32

chromadb:
  collection_name: "mcat"  # Default collection for backward compatibility
  distance_metric: "cosine"
  auth_token: "$chromadb_token"  # Generated secret

# Database configurations - each database maps to a ChromaDB collection
databases:
  default:  # Used when no database specified
    vault_subpath: ""  # Sync entire vault
    collection: "homeschool"
  essay:
    vault_subpath: "essays"  # Sync only essays subdirectory
    collection: "essay_collection"
  homework:
    vault_subpath: "homework"
    collection: "homework_collection"

sync:
  exclude_patterns:
    - "**/*.tmp"
    - "**/*.log"
    - "**/.git/**"
  prune_deleted: true
  embed_batch_size: 32

jan:
  base_url: "http://localhost:1337/v1"
  inference_model: "Jan-v3.5-4B-Q4_K_XL"
  embedding_model: "Nomic_embedding"
EOF

echo -e "${GREEN}Configuration saved to config.yaml${NC}"

# Validate the created config
if [[ ! -f "config.yaml" ]]; then
    echo -e "${RED}Error: Failed to create config.yaml${NC}"
    exit 1
fi

echo -e "${GREEN}Starting Docker services...${NC}"
 
# Launch Docker services
if cd .docker && docker compose up -d; then
    echo -e "${GREEN}Docker services started successfully!${NC}"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "1. Services are now running in the background"
    echo "2. To check status: docker compose ps"
    echo "3. To view logs: docker compose logs -f"
    echo "4. To stop services: docker compose down"
    echo ""
    echo -e "${GREEN}Setup complete! For future runs, simply use:${NC}"
    echo "  docker compose up -d"
else
    echo -e "${RED}Error: Failed to start Docker services${NC}"
    echo "Please check that Docker is installed and running correctly."
    exit 1
fi